atomic/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls', namespace='blog')),
    url(r'^', include('dashboard.urls')),
    url(r'^summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url

from . import views

from django.contrib.sitemaps.views import sitemap
from sitemap import ViewSitemap, BlogSitemap

# a dictionary of sitemaps
sitemaps = {
    'views': ViewSitemap,
    'blog': BlogSitemap
}

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.SoonView.as_view(), name='index'),
    url(r'^blog/(?P<slug>[^\.]+)/$', views.BlogPostView.as_view(), name='blog-post'),
    url(r'^work/(?P<slug>[^\.]+)/$', views.WorkDetailView.as_view(), name='project'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^hire/$', views.hire, name='hire'),
    url(r'^plans/$', views.PlansView.as_view(), name='plans'),
    url(r'^services/$', views.ServicesView.as_view(), name='services'),
    url(r'^faq/$', views.FaqView.as_view(), name='faq'),
    url(r'^coming-soon/$', views.SoonView.as_view(), name='soon'),
    url(r'^work/$', views.ProjectListView.as_view(), name='work'),
    url(r'^blog/$', views.BlogListView.as_view(), name='blog'),
    url(r'^thanks/$', views.ThanksView.as_view(), name='thanks'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
import datetime

class Post(models.Model):
	name = models.CharField(max_length=200)
	email = models.CharField(max_length=200)
	project_choices = (
        ('web', 'Web Development'),
    	('mobile', 'Mobile Development'),
        ('strategy', 'Digital Strategy'),
    	('other', 'Other'),
    	)
	project = models.CharField(choices=project_choices, max_length=200)
	status_choices = (
    	('new', 'New'),
    	('existing', 'Existing'),
    	)
	status = models.CharField(choices=status_choices, max_length=200)
	timeline_choices = (
    	('now', 'Now'),
    	('week', 'One Week'),
    	('month', 'One Month'),
    	('months', 'Two Months'),
    	)
	timeline = models.CharField(choices=timeline_choices, max_length=200)
	created_at = models.DateTimeField(db_index=True, auto_now_add=True, null=True)

	def __str__(self):
		return self.email

class Project(models.Model):
    name = models.CharField(max_length=200, blank=True)
    slug = models.SlugField(max_length=200, unique=True)
    image1 = models.FileField(upload_to='images/%Y%m%d', blank=True)
    image2 = models.FileField(upload_to='images/%Y%m%d', blank=True)
    image3 = models.FileField(upload_to='images/%Y%m%d', blank=True)
    image4 = models.FileField(upload_to='images/%Y%m%d', blank=True)
    excerpt = models.CharField(max_length=200, blank=True)
    description1 = models.TextField(blank=True)
    description2 = models.TextField(blank=True)
    description3 = models.TextField(blank=True)
    link = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=200, blank=True)
    image = models.FileField(upload_to='images/%Y%m%d', blank=True)
    is_draft = models.BooleanField(default=False, blank=True)
    slug = models.SlugField(max_length=200, unique=True)
    excerpt = models.CharField(max_length=200, blank=True)
    body = models.TextField(blank=True)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog-post', kwargs={'slug':self.slug})

blog/forms.py
from django import forms
 
class PostForm(forms.Form):
    project_choices = (
    	('mobile', 'Mobile'),
    	('web', 'Web'),
    	('other', 'Other'),
    )
    project = forms.ChoiceField(choices=project_choices)
    status_choices = (
    	('new', 'New'),
    	('existing', 'Existing'),
    )
    status = forms.ChoiceField(choices=status_choices)
    timeline_choices = (
    	('now', 'Now'),
    	('week', 'One Week'),
    	('month', 'One Month'),
    	('months', 'Two Months'),
    )
    timeline = forms.ChoiceField(choices=timeline_choices)
    name = forms.CharField(max_length=200)
    email = forms.CharField(max_length=200)

blog/views.py
from django.shortcuts import render
from django.views import generic
from .forms import PostForm
from django.utils import timezone
from django.http import HttpResponseRedirect, HttpResponse
from .models import Post, Project, Blog
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template

class IndexView(generic.TemplateView):
    template_name = "blog/index2.html"

class AboutView(generic.TemplateView):
    template_name = "blog/about.html"

class ProjectListView(generic.ListView):
    template_name = 'blog/work.html'
    context_object_name = 'projects_list'
    model = Project

    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)

        return context

class WorkDetailView(generic.DetailView):
    model = Project
    template_name = 'blog/project.html'

class SoonView(generic.TemplateView):
    template_name = "blog/soon.html"

class PlansView(generic.TemplateView):
    template_name = "blog/plans.html"

class ThanksView(generic.TemplateView):
    template_name = "blog/thanks.html"

class FaqView(generic.TemplateView):
    template_name = "blog/faq.html"

class ServicesView(generic.TemplateView):
    template_name = "blog/services.html"

class BlogListView(generic.ListView):
    template_name = 'blog/blog.html'
    model = Blog

    def get_context_data(self, **kwargs):
        context = super(BlogListView, self).get_context_data(**kwargs)
        context['blog_list'] = Blog.objects.order_by('-created_at')

        return context

class BlogPostView(generic.DetailView):
    model = Blog
    template_name = 'blog/blog-post.html'

def hire(request):
    if request.method == 'GET':
        form = PostForm()
    else:
        form = PostForm(request.POST, request.FILES)
 
        if form.is_valid():

            post = Post.objects.create(
                project = form.cleaned_data['project'],
                status = form.cleaned_data['status'],
                timeline = form.cleaned_data['timeline'],
                name = form.cleaned_data['name'],
                email = form.cleaned_data['email'],
                created_at = timezone.now()
                )
            
            plaintext = get_template('blog/emails/confirmation_email.txt')
            htmly     = get_template('blog/emails/confirmation_email.html')
            subject = 'We received your project info'        

            from_email, to = 'Team Attomik <hello@attomik.ccom>', form.cleaned_data['email']
            text_content = plaintext.render()
            html_content = htmly.render()
            mail = EmailMultiAlternatives(subject, text_content, from_email, [to])
            mail.attach_alternative(html_content, "text/html")
            mail.send()

            return HttpResponseRedirect('/thanks/')

        else:
            print form.is_valid()   #form contains data and errors
            print form.errors
 
    return render(request, 'blog/hire.html', {
        'form': form,
    })

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block meta %}
<title>About Us | Attomik Digital Agency</title>
<meta property="og:url" content="http://attomik.com/about/">
<meta property="og:title" content="About Us | Attomik Digital Agency">
<meta name="description" content="At Attomik, we have experience building an extensive number of projects across many industries. We are here to help you develop your next big project.">
<meta property="og:description" content="At Attomik, we have experience building an extensive number of projects across many industries. We are here to help you develop your next big project.">
<meta name="twitter:image" content="http://attomik.com/media/images/20180705/attomik.png">
<meta property="og:image" content="http://attomik.com/media/images/20180705/attomik.png">
{% endblock %}
{% block content %}

<div class="block block-inverse  app-header"
     style="background-image: url({% static 'blog/assets/img/bg1.jpg' %});">

  <div class="container py-4 fixed-top app-navbar">
  <nav class="navbar navbar-transparent navbar-padded navbar-toggleable-sm">
    <button
      class="navbar-toggler navbar-toggler-right hidden-md-up"
      type="button"
      data-target="#stage"
      data-toggle="stage"
      data-distance="-250">
      <span class="navbar-toggler-icon"></span>
    </button>

    <a class="navbar-brand mr-auto" href="{% url 'blog:index' %}">
      <img src="{% static 'blog/assets/img/physics.svg' %}" style="width:20px" alt="attomik coding">
      Attomik
    </a>

    <div class="hidden-sm-down text-uppercase">
      <ul class="navbar-nav">
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
        </li>
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'blog:about' %}">About</a>
        </li>
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'blog:work' %}">Work</a>
        </li>
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'blog:blog' %}">Blog</a>
        </li>
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'blog:hire' %}">Let's Talk</a>
        </li>
      </ul>
    </div>
  </nav>
</div>
</div>

<div class="block block-bordered-lg">
  <div class="container text-center app-translate-15" data-transition="entrance">
    <blockquote class="pull-quote">
      <p>
        The right <span class="text-primary">digital partner</span> with extraordinary developers, engineers and designers
      </p>
    </blockquote>
  </div>
</div>


<div class="block block-bordered-lg pb-0 app-block-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-7 col-md-6 text-center">
        <h1>More About Us</h1>
        <img
          src="{% static 'blog/assets/img/startup-02.svg' %}"
          class="app-translate-5"
          data-transition="entrance"
          style="width:100%">
      </div>
      <div class="col-lg-5 col-md-6 text-center text-md-left pb-5">
        <p class="lead">
          We have experience building an extensive number of projects across many industries. We are here to help you develop your next big project no matter what it is.
        </p>
        <div class="row my-4">
          <div class="col-6 mb-3">
            <div class="statcard">
              <h2 class="statcard-number block-title" style="font-size:42px">50+</h2>
              <span class="statcard-desc">Websites</span>
            </div>
          </div>
          <div class="col-6 mb-3">
            <div class="statcard">
              <h2 style="font-size:42px" class="statcard-number block-title">30+</h2>
              <span class="statcard-desc">Mobile Apps</span>
            </div>
          </div>
        </div>
        <div class="row mb-3">
          <div class="col-6 mb-3">
            <div class="statcard">
              <h2 style="font-size:42px" class="statcard-number block-title">20+</h2>
              <span class="statcard-desc">Digital Strategies</span>
            </div>
          </div>
          <div class="col-6 mb-3">
            <div class="statcard">
              <h2 style="font-size:42px" class="statcard-number block-title text-primary">97%</h2>
              <span class="statcard-desc">Satisfaction</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="block block-inverse app-high-praise"
     style="background-image: url({% static 'blog/assets/img/tal.png' %});">
    <div class="container">
      <div class="row app-align-center py-3">
        <div class="col-sm-5 push-sm-7 py-5">
          <h6 class="text-muted text-uppercase mb-2">Our team</h6>
          <h3 class="mb-4">Developers hand picked by developers, not recruiters</h3>
        </div>
      </div>
  </div>
</div>
<div class="block block-bordered-lg ">
  <div class="col-sm-8 offset-sm-2">
    <p class="lead mx-auto text-center">
      Our developers and designers have deep experience building complex projects and are leaders in their expertise areas
    </p>
    <br>
    <br>
    <div class="row my-4">
    <div class="col-sm-6">
      <ul class="featured-list featured-list-bordered">
        <li class="mb-5">
          <div class="featured-list-icon">
            <span class="fa fa-users text-primary"></span>
          </div>

          <h3>Community Leaders</h3>
          <p>
            Oue network members are leaders in developer communities like AngularJS, GO, Python and many more.
          </p>
        </li>

        <li>
          <div class="featured-list-icon">
            <span class="fa fa-code text-primary"></span>
          </div>
          <h3>Hackathons Won</h3>
          <p>
            A team of winners. At Attomik you find the people who stands out over the crowd.
          </p>
        </li>
      </ul>
    </div>
    <div class="col-sm-6">
      <ul class="featured-list featured-list-bordered">
        <li class="mb-5">
          <div class="featured-list-icon">
            <span class="fa fa-trophy text-primary"></span>
          </div>

          <h3>Company awards</h3>
          <p>
            Apps and sites built by our members have been recognized by some of the best companies.
          </p>
        </li>

        <li>
          <div class="featured-list-icon">
            <span class="fa fa-microchip text-primary"></span>
          </div>
          <h3>Robots Built</h3>
          <p>
            Not only software but also hardware, our developers can thrive in a lot of areas and help you with any project.
          </p>
        </li>
      </ul>
    </div>
  </div>
  </div>
</div>
<div class="block block-bordered">
  <div class="container">
    <div class="row app-align-center">

      <div class="col-sm-5 hidden-sm-down">
        <div class="imgborder s1 s3" 
        style="background-image:url('{% static 'blog/assets/img/ben.png' %}');
        width:100%;
        height:300px;
        background-size:cover;
        background-position:center
        ">
        </div>
      </div>

      <div class="col-md-6 offset-md-1 col-sm-12 offset-sm-0">
        <h6 class="text-muted text-uppercase">Our Team</h6>
        <h3>Why Us</h3>
        <p class="mb-4 text-justify">
            At  Attomik,  we’re all about the experience. We design simple, compelling, and functional digital strategies that make it easy for users to quickly find exactly what they’re looking and then convert them into customers. It’s about creating a online experience that transforms users into followers and customers into ambassadors.
            <br><br>
            We do this by listening to you, understanding your target audience, and putting our extensive online knowledge to work on a plan that will improve your business goals and change the way you think about the potential of the internet.
        </p>
        <!--<div class="row hidden-md-down">
          <div class="col-sm-6 mb-3">
            <h5>Data frequency</h5>
            <p>We’ve formed a compact, close-knit team of highly effective A+ players, each with expansive knowledge of his/her realm, and unparalleled attention to detail. <a href="#" class="text-primary">Learn more.</a></p>
          </div>
          <div class="col-sm-6">
            <h5>Reliability &amp; uptime</h5>
            <p>We process our data across a massively distributed network of reliable servers to ensure 99.99% uptime, always. <a href="#" class="text-primary">Learn more</a>.</p>
          </div>
        </div>-->
      </div>
    </div>

  </div>
</div>
<div class="block app-price-plans">
  <div class="container text-center">

    <div class="row mb-5">
      <div class="col-md-8 offset-md-2 col-lg-6 offset-lg-3">
        <h6 class="text-muted text-uppercase mb-2">Attomik</h6>
        <h3>We are the right partner to help you get your projects from 0 to 1</h3>
      </div>
    </div>

    <div class="row">
      <div class="offset-md-4 col-md-4 px-4 pb-2 mb-5">

        <a href="{% url 'blog:hire' %}" class="btn btn-lg btn-primary btn-block">
          Talk to us
        </a>
      </div>
    </div>

  </div>
</div>

{% endblock %}`

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
  <head>

    {% load staticfiles %}

    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="attomik, digital agency, digital, agancy, seo, marketing, software, developers, designers, digital strategy, new york">
    <meta name="author" content="Attomik">
    <meta property="og:type"   content="website" /> 
    <meta name="thumbnail" content="http://attomik.com/media/images/20180705/attomik.png" />
    <meta name="twitter:card" content="summary_large_image">

    <meta property="og:site_name" content="Attomik">
    <meta name="twitter:image:alt" content="Attomik">

    <meta property="fb:app_id" content="210102709641085" />
    <meta name="twitter:site" content="@TeamAttomik">

    <meta name="google-site-verification" content="knlWMbC7_CWUmg1AiH9x23F-NwO91wtSvBtY2BHYaVg" />

    {% block meta %}{% endblock %}


    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'blog/assets/img/physics.png' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'blog/assets/img/physics.png' %}" type="image/x-icon">

    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Lora:400,400italic|Work+Sans:300,400,500,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <!-- Styles -->
    <link href="{% static 'blog/assets/css/toolkit-startup.css' %}" rel="stylesheet">
    <link href="{% static 'blog/assets/css/application-startup.css' %}" rel="stylesheet">
    <link href="{% static 'blog/assets/css/main.css' %}" rel="stylesheet">
    <link href="{% static 'blog/assets/css/animate.css' %}" rel="stylesheet">

    <script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5b70b19a86b6440010e0309f&product='inline-share-buttons" async="async"></script>

    <style>
      /* note: this is a hack for ios iframe for bootstrap themes shopify page */
      /* this chunk of css is not part of the toolkit :) */
      /* …curses ios, etc… */
      @media (max-width: 768px) and (-webkit-min-device-pixel-ratio: 2) {
        body {
          width: 1px;
          min-width: 100%;
          *width: 100%;
        }
        #stage {
          height: 1px;
          overflow: auto;
          min-height: 100vh;
          -webkit-overflow-scrolling: touch;
        }
      }
    </style>

    <!-- Google Analytics -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-96929433-1', 'auto');
      ga('send', 'pageview');

    </script>

  </head>


<body>

<div class="stage-shelf stage-shelf-right hidden" id="sidebar">
  <ul class="nav nav-bordered nav-stacked flex-column">
    <li class="nav-header">Main</li>
    <li class="nav-item">
      <a href="{% url 'blog:index' %}" class="nav-link">Home</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'blog:about' %}" class="nav-link">About</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'blog:work' %}" class="nav-link">Work</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'blog:blog' %}" class="nav-link">Blog</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'blog:hire' %}" class="nav-link">Let's Talk</a>
    </li>
  </ul>
</div>

<div class="stage" id="stage">

  {% block content %}
  {% endblock %}

  <div class="block block-inverse app-footer">
   <div class="container">
      <div class="row">
        <div class="col-md-5 mb-5">
          <ul class="list-unstyled list-spaced">
            <li class="mb-2"><h6 class="text-uppercase">About</h6></li>
            <li class="text-muted text-justify">
               Attomik is a NYC based digital agency that helps great companies with their digital needs. The right team for your digital projects. Want to learn more? Send us an email to <a href="mailto: hello@attomik.com">hello@attomik.com</a>.
            </li>
          </ul>
        </div>
        <div class="col-md-2 offset-md-3">
          <ul class="list-unstyled list-spaced">
            <li class="mb-2"><h6 class="text-uppercase">Main</h6></li>
            <li class="text-muted"><a href="{% url 'blog:index' %}">Home</a></li>
            <li class="text-muted"><a href="{% url 'blog:about' %}">About</a></li>
            <li class="text-muted"><a href="{% url 'blog:work' %}">Work</a></li>
            <li class="text-muted"><a href="{% url 'blog:blog' %}">Blog</a></li>
            <li class="text-muted"><a href="{% url 'blog:hire' %}">Let's Talk</a></li>
          </ul>
        </div>
        <div class="col-md-2 mb-5">
          <ul class="list-unstyled list-spaced">
            <li class="mb-2"><h6 class="text-uppercase">Contact</h6></li>
            <li class="text-muted">119 W 24th New York NY 10011</li>
            <li class="text-muted"><a href="mailto:hello@attomik.com">hello@attomik.com</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

</div>

    <script src="{% static 'blog/assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'blog/assets/js/tether.min.js' %}"></script>
    <script src="{% static 'blog/assets/js/toolkit.js' %}"></script>
    <script src="{% static 'blog/assets/js/main.js' %}"></script>
    <script src="{% static 'blog/assets/js/application.js' %}"></script>
  </body>
</html>

blog/templates/blog/work.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block meta %}
<title>Work | Attomik Digital Agency</title>
<meta property="og:url" content="http://attomik.com/work/">
<meta property="og:title" content="Work | Attomik Digital Agency">
<meta name="description" content="At Attomik, we've worked with great companies facing different challenges. We help any type of company develop a winning. digital strategy.">
<meta property="og:description" content="At Attomik, we've worked with great companies facing different challenges. We help any type of company develop a winning. digital strategy.">
<meta name="twitter:image" content="http://attomik.com/media/images/20180705/attomik.png">
<meta property="og:image" content="http://attomik.com/media/images/20180705/attomik.png">
{% endblock %}
{% block content %}

<div class="block block-inverse  app-header"
     style="background-image: url({% static 'blog/assets/img/bg1.jpg' %});">

  <div class="container py-4 fixed-top app-navbar">
  <nav class="navbar navbar-transparent navbar-padded navbar-toggleable-sm">
    <button
      class="navbar-toggler navbar-toggler-right hidden-md-up"
      type="button"
      data-target="#stage"
      data-toggle="stage"
      data-distance="-250">
      <span class="navbar-toggler-icon"></span>
    </button>

    <a class="navbar-brand mr-auto" href="{% url 'blog:index' %}">
      <img alt="attomik" src="{% static 'blog/assets/img/physics.svg' %}" style="width:20px">
      Attomik
    </a>

    <div class="hidden-sm-down text-uppercase">
      <ul class="navbar-nav">
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
        </li>
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'blog:about' %}">About</a>
        </li>
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'blog:work' %}">Work</a>
        </li>
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'blog:blog' %}">Blog</a>
        </li>
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'blog:hire' %}">Let's Talk</a>
        </li>
      </ul>
    </div>
  </nav>
</div>
</div>



<div class="block text-center">
  <div class="container-fluid">
   <blockquote class="pull-quote">
      <p>
        “Finding the <span class="text-primary">right partner</span> is an absolute necessity to build a business this days, <span class="text-primary">Attomik</span> has helped us win on digital”
      </p>
      <cite>Sarah Pool, <a href="https://drinkcanvas.com" target="_blank">Canvas</a> Founder</cite>
    </blockquote>
  </div>
</div>
<h1 class="text-center mb-5">Our Latest Work</h1>
{% for project in projects_list %}
{% if forloop.counter|divisibleby:2 %}
<div class="block block-bordered">
  <div class="container">
    <div class="row app-align-center">

      <div class="col-sm-12 hidden-md-up">
        <div title="{{project.name}}" class="imgborder s1 s3" 
        style="background-image:url('{{project.image1.url}}');
        width:100%;
        height:300px;
        background-size:cover;
        background-position:center
        ">
        </div>
      </div>

       <div class="col-md-6 offset-md-1 col-sm-12 offset-sm-0">
        <h6 class="text-muted text-uppercase">Case Studies</h6>
        <h3><a href="{% url 'blog:project' project.slug %}" style="color:black">{{project.name}}</a></h3>
        <p class="lead mb-4">{{project.excerpt}}</p>
        <p class="mb-4 text-justify" style="font-size:18px">{{project.description1|truncatechars:190}}</p>
        <a href="{% url 'blog:project' project.slug %}" class="btn btn-primary">Read More</a>
      </div>

      <div class="col-sm-5 hidden-sm-down">
        <div title="{{project.name}}" class="imgborder s1 s3" 
        style="background-image:url('{{project.image1.url}}');
        width:100%;
        height:300px;
        background-size:cover;
        background-position:center
        ">
        </div>
      </div>
    </div>

  </div>
</div>
{% else %}
<div class="block block-bordered">
  <div class="container">
    <div class="row app-align-center">

      <div class="col-sm-5 hidden-sm-down">
        <div title="{{project.name}}" class="imgborder s1 s3" 
        style="background-image:url('{{project.image1.url}}');
        width:100%;
        height:300px;
        background-size:cover;
        background-position:center
        ">
        </div>
      </div>

      <div class="col-sm-12 hidden-md-up">
        <div title="{{project.name}}" class="imgborder s1 s3" 
        style="background-image:url('{{project.image1.url}}');
        width:100%;
        height:300px;
        background-size:cover;
        background-position:center
        ">
        </div>
      </div>

      <div class="col-md-6 offset-md-1 col-sm-12 offset-sm-0">
        <h6 class="text-muted text-uppercase">Case Studies</h6>
        <h3><a href="{% url 'blog:project' project.slug %}" style="color:black">{{project.name}}</a></h3>
        <p class="lead mb-4">{{project.excerpt}}</p>
        <p class="mb-4 text-justify" style="font-size:18px">{{project.description1|truncatechars:190}}</p>
        <a href="{% url 'blog:project' project.slug %}" class="btn btn-primary">Read More</a>
      </div>
    </div>

  </div>
</div>
{% endif %}
{% endfor %}
<div class="block app-price-plans">
  <div class="container text-center">

    <div class="row mb-5">
      <div class="col-md-8 offset-md-2 col-lg-6 offset-lg-3">
        <h6 class="text-muted text-uppercase mb-2">Attomik</h6>
        <h3>We are the right partner to help you get your projects from 0 to 1</h3>
      </div>
    </div>

    <div class="row">
      <div class="offset-md-4 col-md-4 px-4 pb-2 mb-5">

        <a href="{% url 'blog:hire' %}" class="btn btn-lg btn-primary btn-block">
          Talk to us
        </a>
      </div>
    </div>

  </div>
</div>

{% endblock %}