atomic/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls', namespace='blog')),
    url(r'^', include('dashboard.urls')),
    url(r'^summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url

from . import views

from django.contrib.sitemaps.views import sitemap
from sitemap import ViewSitemap, BlogSitemap

# a dictionary of sitemaps
sitemaps = {
    'views': ViewSitemap,
    'blog': BlogSitemap
}

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.SoonView.as_view(), name='index'),
    url(r'^blog/(?P<slug>[^\.]+)/$', views.BlogPostView.as_view(), name='blog-post'),
    url(r'^work/(?P<slug>[^\.]+)/$', views.WorkDetailView.as_view(), name='project'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^hire/$', views.hire, name='hire'),
    url(r'^plans/$', views.PlansView.as_view(), name='plans'),
    url(r'^services/$', views.ServicesView.as_view(), name='services'),
    url(r'^faq/$', views.FaqView.as_view(), name='faq'),
    url(r'^coming-soon/$', views.SoonView.as_view(), name='soon'),
    url(r'^work/$', views.ProjectListView.as_view(), name='work'),
    url(r'^blog/$', views.BlogListView.as_view(), name='blog'),
    url(r'^thanks/$', views.ThanksView.as_view(), name='thanks'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

dashboard/urls.py
from django.conf.urls import url

from . import views

app_name = 'dashboard'
urlpatterns = [
    url(r'^dashboard/user_acquisition/strategy$', views.StrategyView.as_view(), name='strategy'),
    url(r'^dashboard/user_acquisition/seo$', views.SeoView.as_view(), name='seo'),
    url(r'^dashboard/user_acquisition/seo/checklist$', views.SeoChecklistView.as_view(), name='seo-checklist'),
    url(r'^dashboard/user_acquisition/objective-first$', views.ObjectiveFirstView.as_view(), name='objective-first'),
    url(r'^dashboard/freelancers/$', views.FreelancerListView.as_view(), name='freelancers'),
]

dashboard/models.py
from __future__ import unicode_literals

from django.db import models

class Freelancer(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    profile_image = models.FileField(upload_to='images/%Y%m%d')
    title = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    overview = models.TextField()
    skills = models.TextField()
    english_choices = (
        ('poor', 'Poor'),
        ('basic', 'Basic'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced'),
        )
    english = models.CharField(choices=english_choices, max_length=200)
    work_history = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email

dashboard/views.py
from django.shortcuts import render
from django.views import generic
from .models import Freelancer

class DashboardView(generic.TemplateView):
    template_name = "dashboard/index.html"

class StrategyView(generic.TemplateView):
    template_name = "dashboard/ua/strategy.html"

class SeoView(generic.TemplateView):
    template_name = "dashboard/ua/seo.html"

class ObjectiveFirstView(generic.TemplateView):
    template_name = "dashboard/ua/objective-first.html"

class SeoChecklistView(generic.TemplateView):
    template_name = "dashboard/ua/seo-checklist.html"

class FreelancerListView(generic.ListView):
    template_name = 'dashboard/freelancers.html'
    context_object_name = 'freelancers_list'

    def get_queryset(self):
        return Freelancer.objects.order_by('-created_at')

dashboard/templates/dashboard/freelancers.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="wrapper">
    
    {% include 'dashboard/sidebar.html' %}

    <div class="main-panel">

        {% include 'dashboard/navbar.html' %}

        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    {% for freelancer in freelancers_list %}
                    <div class="col-sm-4">
                        <div class="card card-user">
                            <div class="image">
                                <img src="http://dailygenius.com/wp-content/uploads/2014/06/coding_my_life_away_by_izzuthug-d4dgn1d.png" alt="..."/>
                            </div>
                            <div class="content">
                                <div class="author">
                                    <img class="avatar border-gray" src="{{freelancer.profile_image.url}}" alt="..."/>

                                      <h4 class="title">
                                      {{freelancer.first_name}} {{freelancer.last_name}}<br />
                                         <small>{{freelancer.email}}</small>
                                      </h4>
                                </div>
                                <p class="description text-center"> 
                                    {{freelancer.title}}
                                </p>
                                <div class="text-center">
                                    <p>
                                    <span class="label label-primary">{{freelancer.skills}}</span>
                                    </p>
                                    <p>
                                    <span class="label label-success">{{freelancer.english|title}} English</span>
                                    </p>
                                </div>
                                <div class="text-justify">
                                    {{freelancer.overview}}
                                </div>
                                <br>
                                <div class="text-center">
                                    <span class="text-muted">{{freelancer.work_history}}</span>
                                </div>

                            </div>
                            <hr>
                            <div class="text-center">
                                <button href="#" class="btn btn-simple"><i class="fa fa-map-marker text-success"></i></button>{{freelancer.city}}, {{freelancer.country}}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}
{% block bread_crumbs %}
<h3 class="text-themecolor m-b-0 m-t-0">Business and Customer Strategy</h3>
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
    <li class="breadcrumb-item active">Dashboard</li>
</ol>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card text-justify">
            <div class="card-body">
                <h4 class="card-title">Business & Customer Strategy</h4>
                <h6 class="card-subtitle">Use this tool to add all info around your business and customer strategy</h6>
                <p><b class="text-primary">Digital Marketing</b> is always a changing system. It’s measurable, iterable, and we can optimize accurately.</p>
                <p>The most important part of the customer acquisition journey is to clearly understand who are you targeting, where to reach them and how. For that, you have to make sure you understand what your value proposition is.</p>
                <p>A value proposition answers the question... “Why am I better off with this product, good, or service?</p>
                <p><b>How do customers interpret value?</b></p>
                <ol>
                    <li><b class="text-success">Psychological</b>: emotional or inexplicable benefits “It makes me feel good”</li>
                    <li><b class="text-success">Economically</b>: financial benefits “Buy this one to save money”</li>
                    <li><b class="text-success">Functional</b>: utility gained from the product or service “Helps me do things better or faster”</li>
                </ol>
                <p>The popular way to communicate it clearly and concisely is an <b class="text-primary">ELEVATOR PITCH</b>.</p>
            </div>
        </div>
        <div class="card text-justify">
            <div class="card-body">

                <h4 class="card-title">Elevator Pitch</h4>

                <p>It’s how you express your customer value. It can change based on the person that you’re talking to.</p>

                <p><b class="text-primary">Elevator Pitch sentence structure:</b></p>

                <p>FOR (target customer), WHO HAS (customer need), (product name) IS A (market category) THAT (one key benefit) UNLIKE (competition), THE PRODUCT (unique differentiation).</p>

                <p>
                  <a class="btn btn-success" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                    Example and Tips
                  </a>
                </p>
                <div class="collapse" id="collapseExample">
                  <div class="card card-body">
                    <p><b class="text-success">Example Elevator Pitch:</b></p>

                    <p>For young and connected people, who have the need of getting groceries, this company is an on-demand service that unlike groceries stores, will get beer delivered to your home.</p>

                    <p><b class="text-success">Some tips:</b></p>
                    <ul>
                        <li>Elevator pitches are used both internally and externally but, for our purposes, try to use the customer’s voice instead of internal jargon.</li>
                        <li>There are trade offs to naming vs. describing your business’ competition. </li>
                        <li>Instead of your company’s name, you may need to describe:
                            <ol>
                                <li>Its market category</li>
                                <li>One key benefit</li>
                                <li>A unique differentiator</li>
                            </ol>
                        </li>
                    </ul>
                  </div>
                </div>
                <form class="floating-labels m-t-40">
                    <div class="form-group m-b-40">
                        <textarea class="form-control" rows="4" id="input1"></textarea>
                        <span class="bar"></span>
                        <label for="input1">Write your elevator pitch here...</label>
                    </div>
                </form>
            </div>
        </div>
        <div class="card text-justify">
            <div class="card-body">

                <h4 class="card-title">Customer Persona</h4>

                <p>To define your ideal customer you can take characteristics and create a name, person or character.</p>

                <p>There are different personas. You can identify primary or secondary personas.</p>
                <ul>
                    <li><b class="text-success">Primary persona</b>: who you think your primary revenue driver is</li>
                    <li><b class="text-success">Secondary personas</b>: are others that drive revenue but are more infrequent or sub revenue generators</li>
                </ul>

                <p>
                  <a class="btn btn-success" data-toggle="collapse" href="#collapseExample2" role="button" aria-expanded="false" aria-controls="collapseExample2">
                    Examples
                  </a>
                </p>
                <div class="collapse" id="collapseExample2">
                  <div class="card card-body">
                    <i>Sally is a mom and recently launched her own eCommerce startup. Once upon a time, she had no clue how to build a website, but she figured it out. She runs her business from the desk in the corner of her apartment. It’s covered in Post-Its, unopened mail, and unsealed boxes for customer purchases she’s not yet shipped — it’s safe to say she isn’t fully digital in her business operations. When she isn’t listening to the sound of her own typing replying to customer inquiries, she hears the sounds of toddler gurgles or the TV running in the background (always tuned the local news), which drown out the city sirens. Sally lives between the physical and digital worlds. She still subscribes to some paper magazines (Vogue and Vanity Fair), while consuming others (Inc. & Real Simple) on her iPhone. She doesn’t have time for social media and finds that it depresses her, but she always makes time to volunteer at a local women’s shelter. It’s safe to say that she has her hands full. Everything she does, she does to create a better world for her son.</i>
                    <br>
                    <img class="card-img-top img-responsive" style="max-width:700px" src="{% static 'dashboard/assets/img/ua/customer_persona.png' %}" alt="customer persona">
                  </div>
                </div>
                <form class="floating-labels m-t-40">
                    <div class="form-group m-b-40">
                        <textarea class="form-control" rows="4" id="input2"></textarea>
                        <span class="bar"></span>
                        <label for="input2">Define your customer persona here...</label>
                    </div>
                </form>
            </div>
        </div>
         <div class="card text-justify">
            <div class="card-body">

                <h4 class="card-title">Empathy Map</h4>

                <p>Customer Empathy Maps help you expand your personas. They focus on further defining a customer’s motivations, needs and behaviors. It makes the persona a bit more human.</p>

                <p>
                  <a class="btn btn-success" data-toggle="collapse" href="#collapseExample2" role="button" aria-expanded="false" aria-controls="collapseExample2">
                    Examples
                  </a>
                </p>
                <div class="collapse" id="collapseExample2">
                  <div class="card card-body">
                    <i>Sally is a mom and recently launched her own eCommerce startup. Once upon a time, she had no clue how to build a website, but she figured it out. She runs her business from the desk in the corner of her apartment. It’s covered in Post-Its, unopened mail, and unsealed boxes for customer purchases she’s not yet shipped — it’s safe to say she isn’t fully digital in her business operations. When she isn’t listening to the sound of her own typing replying to customer inquiries, she hears the sounds of toddler gurgles or the TV running in the background (always tuned the local news), which drown out the city sirens. Sally lives between the physical and digital worlds. She still subscribes to some paper magazines (Vogue and Vanity Fair), while consuming others (Inc. & Real Simple) on her iPhone. She doesn’t have time for social media and finds that it depresses her, but she always makes time to volunteer at a local women’s shelter. It’s safe to say that she has her hands full. Everything she does, she does to create a better world for her son.</i>
                    <br>
                    <img class="card-img-top img-responsive" style="max-width:700px" src="{% static 'dashboard/assets/img/ua/customer_persona.png' %}" alt="customer persona">
                  </div>
                </div>
                <form class="floating-labels m-t-40">
                    <p><b class="text-success">General Data</b>: Age, Sex, Income, Residence, etc.</p>
                    <br>
                    <div class="form-group m-b-40">
                        <textarea class="form-control" rows="4" id="input3"></textarea>
                        <span class="bar"></span>
                        <label for="input3">Add "General" data here...</label>
                    </div>
                    <p><b class="text-success">Think and feel</b>: What really counts? What mayor preoccupations? What worries and aspirations?</p>
                    <br>
                    <div class="form-group m-b-40">
                        <textarea class="form-control" rows="4" id="input3"></textarea>
                        <span class="bar"></span>
                        <label for="input3">Add "Think and Feel" data here...</label>
                    </div>
                    <p><b class="text-success">See</b>: What is their environment? Who are their friends? What's happening int their market?</p>
                    <br>
                    <div class="form-group m-b-40">
                        <textarea class="form-control" rows="4" id="input3"></textarea>
                        <span class="bar"></span>
                        <label for="input3">Add "See" data here...</label>
                    </div>
                    <p><b class="text-success">Say & Do</b>: What is their attitude and behaviour in public? What are their fears and obstacles? How do they measure success?</p>
                    <br>
                    <div class="form-group m-b-40">
                        <textarea class="form-control" rows="4" id="input3"></textarea>
                        <span class="bar"></span>
                        <label for="input3">Add "Say & Do" data here...</label>
                    </div>
                    <p><b class="text-success">Hear</b>: What do their influencers say? What does their boss say? What do their friends say?</p>
                    <br>
                    <div class="form-group m-b-40">
                        <textarea class="form-control" rows="4" id="input3"></textarea>
                        <span class="bar"></span>
                        <label for="input3">Add "Hear" data here...</label>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/navbar.html
<nav class="navbar navbar-default navbar-fixed">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Dashboard</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-dashboard"></i>
						<p class="hidden-lg hidden-md">Dashboard</p>
                    </a>
                </li>
                <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-globe"></i>
                            <b class="caret hidden-sm hidden-xs"></b>
                            <span class="notification hidden-sm hidden-xs">5</span>
							<p class="hidden-lg hidden-md">
								5 Notifications
								<b class="caret"></b>
							</p>
                      </a>
                      <ul class="dropdown-menu">
                        <li><a href="#">Notification 1</a></li>
                        <li><a href="#">Notification 2</a></li>
                        <li><a href="#">Notification 3</a></li>
                        <li><a href="#">Notification 4</a></li>
                        <li><a href="#">Another notification</a></li>
                      </ul>
                </li>
                <li>
                   <a href="">
                        <i class="fa fa-search"></i>
						<p class="hidden-lg hidden-md">Search</p>
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li>
                   <a href="">
                       <p>Account</p>
                    </a>
                </li>
                <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <p>
								Dropdown
								<b class="caret"></b>
							</p>
                      </a>
                      <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                      </ul>
                </li>
                <li>
                    <a href="#">
                        <p>Log out</p>
                    </a>
                </li>
				<li class="separator hidden-lg hidden-md"></li>
            </ul>
        </div>
    </div>
</nav>

dashboard/templates/dashboard/sidebar.html
{% load staticfiles %}
<div class="sidebar" data-color="red" data-image="{% static 'dashboard/assets/img/sidebar-5.jpg' %}">

<!--

    Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
    Tip 2: you can also add an image using data-image tag

-->

	<div class="sidebar-wrapper">
        <div class="logo">
            <a href="http://www.creative-tim.com" class="simple-text">
                Attomik
            </a>
        </div>

        <ul class="nav">
            <li class="active">
                <a href="{% url 'dashboard:dashboard' %}">
                    <i class="pe-7s-graph"></i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li>
                <a href="{% url 'dashboard:freelancers' %}">
                    <i class="pe-7s-users"></i>
                    <p>Freelancers</p>
                </a>
            </li>
			<li class="active-pro">
                <a href="upgrade.html">
                    <i class="pe-7s-rocket"></i>
                    <p>Upgrade to PRO</p>
                </a>
            </li>
        </ul>
	</div>
</div>