atomic/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls', namespace='blog')),
    url(r'^', include('dashboard.urls')),
    url(r'^summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url

from . import views

from django.contrib.sitemaps.views import sitemap
from sitemap import ViewSitemap, BlogSitemap

# a dictionary of sitemaps
sitemaps = {
    'views': ViewSitemap,
    'blog': BlogSitemap
}

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.SoonView.as_view(), name='index'),
    url(r'^blog/(?P<slug>[^\.]+)/$', views.BlogPostView.as_view(), name='blog-post'),
    url(r'^work/(?P<slug>[^\.]+)/$', views.WorkDetailView.as_view(), name='project'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^hire/$', views.hire, name='hire'),
    url(r'^plans/$', views.PlansView.as_view(), name='plans'),
    url(r'^services/$', views.ServicesView.as_view(), name='services'),
    url(r'^faq/$', views.FaqView.as_view(), name='faq'),
    url(r'^coming-soon/$', views.SoonView.as_view(), name='soon'),
    url(r'^work/$', views.ProjectListView.as_view(), name='work'),
    url(r'^blog/$', views.BlogListView.as_view(), name='blog'),
    url(r'^thanks/$', views.ThanksView.as_view(), name='thanks'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

dashboard/urls.py
from django.conf.urls import url

from . import views

app_name = 'dashboard'
urlpatterns = [
    url(r'^dashboard/user_acquisition/strategy$', views.StrategyView.as_view(), name='strategy'),
    url(r'^dashboard/user_acquisition/seo$', views.SeoView.as_view(), name='seo'),
    url(r'^dashboard/user_acquisition/seo/checklist$', views.SeoChecklistView.as_view(), name='seo-checklist'),
    url(r'^dashboard/user_acquisition/objective-first$', views.ObjectiveFirstView.as_view(), name='objective-first'),
    url(r'^dashboard/freelancers/$', views.FreelancerListView.as_view(), name='freelancers'),
]

dashboard/models.py
from __future__ import unicode_literals

from django.db import models

class Freelancer(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    profile_image = models.FileField(upload_to='images/%Y%m%d')
    title = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    overview = models.TextField()
    skills = models.TextField()
    english_choices = (
        ('poor', 'Poor'),
        ('basic', 'Basic'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced'),
        )
    english = models.CharField(choices=english_choices, max_length=200)
    work_history = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email

dashboard/views.py
from django.shortcuts import render
from django.views import generic
from .models import Freelancer

class DashboardView(generic.TemplateView):
    template_name = "dashboard/index.html"

class StrategyView(generic.TemplateView):
    template_name = "dashboard/ua/strategy.html"

class SeoView(generic.TemplateView):
    template_name = "dashboard/ua/seo.html"

class ObjectiveFirstView(generic.TemplateView):
    template_name = "dashboard/ua/objective-first.html"

class SeoChecklistView(generic.TemplateView):
    template_name = "dashboard/ua/seo-checklist.html"

class FreelancerListView(generic.ListView):
    template_name = 'dashboard/freelancers.html'
    context_object_name = 'freelancers_list'

    def get_queryset(self):
        return Freelancer.objects.order_by('-created_at')

dashboard/templates/dashboard/ua/objective-first.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}
{% block bread_crumbs %}
<h3 class="text-themecolor m-b-0 m-t-0">Objective First Framework</h3>
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
    <li class="breadcrumb-item">User Acquisition</li>
    <li class="breadcrumb-item active">Objective First Framework</li>
</ol>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card text-justify">
            <div class="card-body">
                <h4 class="card-title">Objective First Framework</h4>
                <h6 class="card-subtitle">This is where we’re going and this is how we’re getting there</h6>
            </div>
        </div>
        <div class="card text-justify">
            <div class="card-body">

                <h4 class="card-title">Set Objective</h4>

                <p>When setting objectives you have to be specific. Use <b class="text-primary">SMART</b>objectives</p>
                <p>Also, you need to know who the customer is before setting your objective.</p>

                <p>
                  <a class="btn btn-success" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                    Example and Tips
                  </a>
                </p>
                <div class="collapse" id="collapseExample">
                  <div class="card card-body">
                    <p><b class="text-success">SMART Objective Structure:</b></p>
                    <p>Our goal this year/quarter/month is to (INCREASE OR DECREASE) (X) by/to (PLUG IN A SPECIFIC %/PLUG IN A SPECIFIC NUMBER OR COUNT) in order to (BLANK (SHOULD BE SPECIFIC & TIED TO BUSINESS MODEL)).</p>

                    <p><b class="text-success">Example SMART Objective:</b></p>
                    <p>Convert 33% of leads with customers within 30 days of initial contact.</p>

                  </div>
                </div>
                <form class="floating-labels m-t-20">
                    <div class="form-group m-b-40">
                        <textarea class="form-control" rows="4" id="input1"></textarea>
                        <span class="bar"></span>
                        <label for="input1">Write your SMART objective here...</label>
                    </div>
                </form>
            </div>
        </div>
        <div class="card text-justify">
            <div class="card-body">

                <h4 class="card-title">Define KPIs</h4>
                <p>With metrics, think broad. With key performance indicators, think deep. </p>
                <p>
                  <a class="btn btn-success" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                    Example and Tips
                  </a>
                </p>
                <div class="collapse" id="collapseExample">
                  <div class="card card-body">
                    <p>KPI: A measurable value that demonstrates how effectively a company is achieving key business objectives. Without establishing and tracking proper key performance indicators, companies would be left in the dark about their performance</p>
                    <p>Metric: A quantifiable measure that is used to track and assess the status of a specific process. Metrics are important because they are comprised of a wide swathe of all trackable areas. </p>
                  </div>
                </div>
                <form class="floating-labels m-t-20">
                    <div class="form-group m-b-40">
                        <textarea class="form-control" rows="4" id="input2"></textarea>
                        <span class="bar"></span>
                        <label for="input2">Define your KPIs here...</label>
                    </div>
                </form>
            </div>
        </div>
        <div class="card text-justify">
            <div class="card-body">

                <h4 class="card-title">Design Tactics</h4>
                <p>With metrics, think broad. With key performance indicators, think deep. </p>
                <p>
                  <a class="btn btn-success" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                    Example and Tips
                  </a>
                </p>
                <div class="collapse" id="collapseExample">
                  <div class="card card-body">
                    <p>KPI: A measurable value that demonstrates how effectively a company is achieving key business objectives. Without establishing and tracking proper key performance indicators, companies would be left in the dark about their performance</p>
                    <p>Metric: A quantifiable measure that is used to track and assess the status of a specific process. Metrics are important because they are comprised of a wide swathe of all trackable areas. </p>
                  </div>
                </div>
                <form class="floating-labels m-t-20">
                    <div class="form-group m-b-40">
                        <textarea class="form-control" rows="4" id="input3"></textarea>
                        <span class="bar"></span>
                        <label for="input3">Define your Tactics here...</label>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/ua/seo-checklist.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}
{% block bread_crumbs %}
<h3 class="text-themecolor m-b-0 m-t-0">SEO Checklist</h3>
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
    <li class="breadcrumb-item">User Acquisition</li>
    <li class="breadcrumb-item">SEO</li>
    <li class="breadcrumb-item active">Checklist</li>
</ol>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card text-justify">
            <div class="card-body">
                <h4 class="card-title">SEO Checklist</h4>
                <h6 class="card-subtitle">Use this tool to do an analysis for SEO on your site</h6>
                <div class="form-group row">
                  <label for="example-text-input" class="col-6 col-form-label">Your Title Tag should clarify who you are and what you are.</label>
                  <div class="col-6">
                    <select class="custom-select col-12" id="inlineFormCustomSelect">
                        <option selected="">Choose...</option>
                        <option value="1">No</option>
                        <option value="2">Yes</option>
                        <option value="3">In Progress</option>
                    </select>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/ua/seo.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}
{% block bread_crumbs %}
<h3 class="text-themecolor m-b-0 m-t-0">Search Engine Optimization</h3>
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
    <li class="breadcrumb-item">User Acquisition</li>
    <li class="breadcrumb-item active">SEO</li>
</ol>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card text-justify">
            <div class="card-body">
                <h4 class="card-title">Search Engine Optimization</h4>
                <h6 class="card-subtitle">Use this tool to work with search engine optimization for your site</h6>
                <p><b class="text-primary">What is SEO?</b></p>
                <p>SEO stands for Search Engine Optimization. It is the practice of improving and promoting a website, in order to increase the number of (non-paid) visitors the site receives from search engines.</p>
                <p><b class="text-primary">Why is it important?</b></p>
                <p>Search is a high-intent channel. If you are a user on a search engine, you are actively looking for a solution to a problem. If your business is not found, it is losing revenue.</p>
                <p><b class="text-primary">Why does it matter?</b></p>
                <p>SEO matters because it’s a high intent marketing channel. That means that whoever is performing the search, is looking for an answer to a question, therefore the probability for conversion is much higher.</p>
                <p>In simple terms, search is the channel that has the better quality of visitors and the highest probability for convertion.</p>
                <p><b class="text-primary">How do I optimize for search engines?</b></p>
                <p>Basically you just have to build your site to answer questions and have the right setup to allow search engines to find your awesome content.</p>
                <p>If you have a page that has your address, you have to ask yourself. What question is that answering? If you have an “about me” page, it has to answer questions about “me”.</p>
                <p>Your answers have to be <b class="text-success">RELEVANT</b> , <b class="text-success">UNIQUE</b> and <b class="text-success">RICH IN CONTENT</b>.</p>
                <p><b class="text-success">Example</b>: To make an address page more rich, relevant and unique, you can add an address and contact number, a google maps link and a map image.</p>
                <p>If you provide answers to those questions you’re going to be ranked higher simply because you become more relevant to whoever performed the search.</p>
                <p><b class="text-success">What to do next?</b>
                <p>Now that you understand the importance of SEO, it’s time to optimize your website to make sure that search engines will show the content to the relevant searchers.</p>
                <p>To do this, click on the following link to get the absolute step-by-step guide to help you make the best out of your site.</p>
                <a href="{% url 'dashboard:seo-checklist' %}"><div class="btn btn-success">Go to SEO Checklist</div></a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/ua/strategy.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}
{% block bread_crumbs %}
<h3 class="text-themecolor m-b-0 m-t-0">Business & Customer Strategy</h3>
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
    <li class="breadcrumb-item">User Acquisition</li>
    <li class="breadcrumb-item active">B&C Strategy</li>
</ol>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card text-justify">
            <div class="card-body">
                <h4 class="card-title">Business & Customer Strategy</h4>
                <h6 class="card-subtitle">Use this tool to add all info around your business and customer strategy</h6>
                <p><b class="text-primary">Digital Marketing</b> is always a changing system. It’s measurable, iterable, and we can optimize accurately.</p>
                <p>The most important part of the customer acquisition journey is to clearly understand who are you targeting, where to reach them and how. For that, you have to make sure you understand what your value proposition is.</p>
                <p>A value proposition answers the question... “Why am I better off with this product, good, or service?</p>
                <p><b>How do customers interpret value?</b></p>
                <ol>
                    <li><b class="text-success">Psychological</b>: emotional or inexplicable benefits “It makes me feel good”</li>
                    <li><b class="text-success">Economically</b>: financial benefits “Buy this one to save money”</li>
                    <li><b class="text-success">Functional</b>: utility gained from the product or service “Helps me do things better or faster”</li>
                </ol>
                <p>The popular way to communicate it clearly and concisely is an <b class="text-primary">ELEVATOR PITCH</b>.</p>
            </div>
        </div>
        <div class="card text-justify">
            <div class="card-body">

                <h4 class="card-title">Elevator Pitch</h4>

                <p>It’s how you express your customer value. It can change based on the person that you’re talking to.</p>

                <p><b class="text-primary">Elevator Pitch sentence structure:</b></p>

                <p>FOR (target customer), WHO HAS (customer need), (product name) IS A (market category) THAT (one key benefit) UNLIKE (competition), THE PRODUCT (unique differentiation).</p>

                <p>
                  <a class="btn btn-success" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                    Example and Tips
                  </a>
                </p>
                <div class="collapse" id="collapseExample">
                  <div class="card card-body">
                    <p><b class="text-success">Example Elevator Pitch:</b></p>

                    <p>For young and connected people, who have the need of getting groceries, this company is an on-demand service that unlike groceries stores, will get beer delivered to your home.</p>

                    <p><b class="text-success">Some tips:</b></p>
                    <ul>
                        <li>Elevator pitches are used both internally and externally but, for our purposes, try to use the customer’s voice instead of internal jargon.</li>
                        <li>There are trade offs to naming vs. describing your business’ competition. </li>
                        <li>Instead of your company’s name, you may need to describe:
                            <ol>
                                <li>Its market category</li>
                                <li>One key benefit</li>
                                <li>A unique differentiator</li>
                            </ol>
                        </li>
                    </ul>
                  </div>
                </div>
                <form class="floating-labels m-t-40">
                    <div class="form-group m-b-40">
                        <textarea class="form-control" rows="4" id="input1"></textarea>
                        <span class="bar"></span>
                        <label for="input1">Write your elevator pitch here...</label>
                    </div>
                </form>
            </div>
        </div>
        <div class="card text-justify">
            <div class="card-body">

                <h4 class="card-title">Customer Persona</h4>

                <p>To define your ideal customer you can take characteristics and create a name, person or character.</p>

                <p>There are different personas. You can identify primary or secondary personas.</p>
                <ul>
                    <li><b class="text-success">Primary persona</b>: who you think your primary revenue driver is</li>
                    <li><b class="text-success">Secondary personas</b>: are others that drive revenue but are more infrequent or sub revenue generators</li>
                </ul>

                <p>
                  <a class="btn btn-success" data-toggle="collapse" href="#collapseExample2" role="button" aria-expanded="false" aria-controls="collapseExample2">
                    Examples
                  </a>
                </p>
                <div class="collapse" id="collapseExample2">
                  <div class="card card-body">
                    <i>Sally is a mom and recently launched her own eCommerce startup. Once upon a time, she had no clue how to build a website, but she figured it out. She runs her business from the desk in the corner of her apartment. It’s covered in Post-Its, unopened mail, and unsealed boxes for customer purchases she’s not yet shipped — it’s safe to say she isn’t fully digital in her business operations. When she isn’t listening to the sound of her own typing replying to customer inquiries, she hears the sounds of toddler gurgles or the TV running in the background (always tuned the local news), which drown out the city sirens. Sally lives between the physical and digital worlds. She still subscribes to some paper magazines (Vogue and Vanity Fair), while consuming others (Inc. & Real Simple) on her iPhone. She doesn’t have time for social media and finds that it depresses her, but she always makes time to volunteer at a local women’s shelter. It’s safe to say that she has her hands full. Everything she does, she does to create a better world for her son.</i>
                    <br>
                    <img class="card-img-top img-responsive" style="max-width:700px" src="{% static 'dashboard/assets/img/ua/customer_persona.png' %}" alt="customer persona">
                  </div>
                </div>
                <form class="floating-labels m-t-40">
                    <div class="form-group m-b-40">
                        <textarea class="form-control" rows="4" id="input2"></textarea>
                        <span class="bar"></span>
                        <label for="input2">Define your customer persona here...</label>
                    </div>
                </form>
            </div>
        </div>
         <div class="card text-justify">
            <div class="card-body">

                <h4 class="card-title">Empathy Map</h4>

                <p>Customer Empathy Maps help you expand your personas. They focus on further defining a customer’s motivations, needs and behaviors. It makes the persona a bit more human.</p>

                <p>
                  <a class="btn btn-success" data-toggle="collapse" href="#collapseExample2" role="button" aria-expanded="false" aria-controls="collapseExample2">
                    Examples
                  </a>
                </p>
                <div class="collapse" id="collapseExample2">
                  <div class="card card-body">
                    <i>Sally is a mom and recently launched her own eCommerce startup. Once upon a time, she had no clue how to build a website, but she figured it out. She runs her business from the desk in the corner of her apartment. It’s covered in Post-Its, unopened mail, and unsealed boxes for customer purchases she’s not yet shipped — it’s safe to say she isn’t fully digital in her business operations. When she isn’t listening to the sound of her own typing replying to customer inquiries, she hears the sounds of toddler gurgles or the TV running in the background (always tuned the local news), which drown out the city sirens. Sally lives between the physical and digital worlds. She still subscribes to some paper magazines (Vogue and Vanity Fair), while consuming others (Inc. & Real Simple) on her iPhone. She doesn’t have time for social media and finds that it depresses her, but she always makes time to volunteer at a local women’s shelter. It’s safe to say that she has her hands full. Everything she does, she does to create a better world for her son.</i>
                    <br>
                    <img class="card-img-top img-responsive" style="max-width:700px" src="{% static 'dashboard/assets/img/ua/customer_persona.png' %}" alt="customer persona">
                  </div>
                </div>
                <form class="floating-labels m-t-40">
                    <p><b class="text-success">General Data</b>: Age, Sex, Income, Residence, etc.</p>
                    <br>
                    <div class="form-group m-b-40">
                        <textarea class="form-control" rows="4" id="input3"></textarea>
                        <span class="bar"></span>
                        <label for="input3">Add "General" data here...</label>
                    </div>
                    <p><b class="text-success">Think and feel</b>: What really counts? What mayor preoccupations? What worries and aspirations?</p>
                    <br>
                    <div class="form-group m-b-40">
                        <textarea class="form-control" rows="4" id="input3"></textarea>
                        <span class="bar"></span>
                        <label for="input3">Add "Think and Feel" data here...</label>
                    </div>
                    <p><b class="text-success">See</b>: What is their environment? Who are their friends? What's happening int their market?</p>
                    <br>
                    <div class="form-group m-b-40">
                        <textarea class="form-control" rows="4" id="input3"></textarea>
                        <span class="bar"></span>
                        <label for="input3">Add "See" data here...</label>
                    </div>
                    <p><b class="text-success">Say & Do</b>: What is their attitude and behaviour in public? What are their fears and obstacles? How do they measure success?</p>
                    <br>
                    <div class="form-group m-b-40">
                        <textarea class="form-control" rows="4" id="input3"></textarea>
                        <span class="bar"></span>
                        <label for="input3">Add "Say & Do" data here...</label>
                    </div>
                    <p><b class="text-success">Hear</b>: What do their influencers say? What does their boss say? What do their friends say?</p>
                    <br>
                    <div class="form-group m-b-40">
                        <textarea class="form-control" rows="4" id="input3"></textarea>
                        <span class="bar"></span>
                        <label for="input3">Add "Hear" data here...</label>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}